spring.application.name=alert
server.port=60
spring.data.mongodb.uri=mongodb://localhost:27017/candlestick_db

# Data Service Configuration
data.service.url=http://localhost:5000

# WebSocket Configuration
spring.websocket.allowed-origins=*